name: PlatformIO build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - uses: actions/checkout@v2

    - name: Copy example config
      run: cp settings.example.h settings.h

    - name: PlatformIO build
      run: platformio run
